const CASES_ACTIONS = {
	SET_CASES: 'SET_CASES',
	UNSET_CASES: 'UNSET_CASES',
	SET_LOADED_CASES: 'SET_LOADED_CASES',
	DELETE_CASE: 'DELETE_CASE',
	EDIT_CASE: 'EDIT_CASE',
	ADD_CASE: 'ADD_CASE',
}

export default CASES_ACTIONS