const OFFICERS_ACTIONS = {
	SET_OFFICERS: 'SET_OFFICERS',
	UNSET_OFFICERS: 'UNSET_OFFICERS',
	SET_LOADED_OFFICERS: 'SET_LOADED_OFFICERS',
	DELETE_OFFICER: 'DELETE_OFFICER',
	EDIT_OFFICER: 'EDIT_OFFICER',
	ADD_OFFICER: 'ADD_OFFICER',
}

export default OFFICERS_ACTIONS